//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFTFtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int newEventId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> BuyPrice { get; set; }
        public Nullable<int> SoldPrice { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<int> CreditScore { get; set; }
    }
}
