//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFTFtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Validation
    {
        public string IdCardNumber { get; set; }
        public byte[] IdCardPicture1 { get; set; }
        public byte[] IdCardPicture2 { get; set; }
        public byte[] StudentCardPicture1 { get; set; }
        public byte[] StudentPicture2 { get; set; }
    }
}
